# Generated by Django 5.1.7 on 2025-03-14 18:42

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=builtins.id, serialize=False)),
                ('name', models.TextField(max_length=45)),
                ('age', models.IntegerField()),
                ('dept', models.TextField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
